---
# Velociraptor Server Configuration for PoC

# Bind address and port for the GUI
GUI:
  bind_address: 127.0.0.1
  bind_port: 8000
  use_tls: true

  # Certificate configuration
  tls_certificate_filename: /var/lib/velociraptor/server.crt
  tls_key_filename: /var/lib/velociraptor/server.key

# Client communication settings
Client:
  server_base_url: https://velociraptor-server:8001/

Frontend:
  bind_address: 127.0.0.1
  bind_port: 8001
  use_tls: true

  # Certificate configuration for client communication
  tls_certificate_filename: /var/lib/velociraptor/server.crt
  tls_key_filename: /var/lib/velociraptor/server.key

# Datastore configuration (file-based for PoC)
Datastore:
  implementation: FileBaseDataStore
  location: /var/lib/velociraptor/data

# Logging configuration
Logging:
  - type: stderr
    level: WARNING

# Users configuration
Users:
  - name: admin
    password_hash: admin  # Change this in production!

# Authentication
Auth:
  google_oauth_client_id: ""

# Logging target
Logging_Service:
  enabled: true
  log_path: /var/lib/velociraptor/logs

# Artifact sources
Artifacts:
  - name: Windows.System.OSInfo
  - name: Linux.System.OSInfo
  - name: Linux.Sys.NetworkConnections
  - name: Linux.Sys.ProcessesByName
  - name: Generic.System.Hostname
  - name: Generic.Applications.Installed

# DFIR Artifacts for triage
Imports:
  - velociraptor/common
  - artifact_exchange

# API configuration
API:
  bind_address: 127.0.0.1
  bind_port: 8003
  use_tls: false  # Optional, can be enabled

# Indexing and search
Hunt:
  enabled: true

# Email configuration (optional)
Mail:
  from_address: velociraptor@localhost
  smtp_server: ""

# Timeout settings
Timeout:
  DefaultClientTimeout: 60
  MonitoringClientTimeout: 120
  DefaultHuntTimeout: 3600

# Frontend timeout
Frontend_Timeout: 300

# Auto-created VQL artifacts
VQLResources:
  enabled: true
